
version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: templateuser
      POSTGRES_PASSWORD: 0528sona
      POSTGRES_DB: templatedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    image: ittadoru/bottemplateposgredb:latest
    container_name: app
    restart: always
    working_dir: /app
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - postgres
    # environment:
    #   DATABASE_URL: postgresql+asyncpg://templateuser:0528sona@postgres:5432/templatedb
    command: >
      bash -c "uvicorn server:app --port 8000 & python bot.py"

volumes:
  pgdata:
