version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env  # берём значения переменных из .env (не коммитьте секреты)
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?must-set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?must-set}
      POSTGRES_DB: ${POSTGRES_DB:?must-set}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    image: saverbot-app
    container_name: bot
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: >
      bash -c "
        while ! pg_isready -h postgres -p 5432 -q -U templateuser; do
          echo 'Waiting for database...'
          sleep 1
        done;
        echo 'Database is ready!';
        alembic upgrade head && watchfiles --filter python 'python bot.py'
      "

  server:
    build: .
    image: saverbot-app
    container_name: server
    restart: always
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: >
      bash -c "uvicorn server:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata:
